venues_by_domain:
  computer_vision:
    tier1: ["CVPR", "ICCV", "ECCV"]
    tier2: ["BMVC", "WACV", "ACCV"]
    medical: ["MICCAI", "IPMI", "ISBI"]
    specialized: ["3DV", "ICCV Workshops"]

  nlp:
    tier1: ["ACL", "EMNLP", "NAACL"]
    tier2: ["COLING", "EACL", "CoNLL"]
    specialized: ["WMT", "SemEval"]

  ml_general:
    tier1: ["NeurIPS", "ICML", "ICLR"]
    tier2: ["AISTATS", "UAI", "COLT"]

  reinforcement_learning:
    specialized: ["AAMAS", "AAAI", "IJCAI"]
    robotics: ["ICRA", "IROS", "RSS"]

  graph_learning:
    specialized: ["WWW", "KDD", "WSDM"]
    theory: ["SODA", "FOCS", "STOC"]

computational_focus_scores:
  "CVPR": 0.9
  "ICCV": 0.9
  "ECCV": 0.85
  "MICCAI": 0.8
  "NeurIPS": 0.95
  "ICML": 0.95
  "ICLR": 0.9
  "ACL": 0.7
  "EMNLP": 0.7
  "NAACL": 0.7
  "AAMAS": 0.8
  "ICRA": 0.85
  "IROS": 0.85
