academic_organizations:
  tier1:
    - "MIT"
    - "Stanford University"
    - "Carnegie Mellon University"
    - "UC Berkeley"
    - "Harvard University"
    - "Princeton University"
  
  tier2:
    - "University of Washington"
    - "NYU"
    - "Columbia University"
    - "University of Chicago"
    - "Yale University"
    - "Caltech"
  
  international:
    - "University of Oxford"
    - "University of Cambridge"
    - "ETH Zurich"
    - "University of Toronto"
    - "McGill University"
    - "EPFL"
    - "Technical University of Munich"
    - "University College London"
  
  research_institutes:
    - "Max Planck Institute"
    - "Allen Institute"
    - "Mila"
    - "Vector Institute"
    - "INRIA"
    - "RIKEN"
    - "CSIRO"

industry_organizations:
  big_tech:
    - "Google"
    - "Google Research"
    - "Google DeepMind"
    - "DeepMind"
    - "OpenAI"
    - "Microsoft Research"
    - "Meta AI"
    - "Facebook AI Research"
    - "Apple"
    - "Amazon"
    - "NVIDIA"
    - "Intel Labs"
  
  ai_companies:
    - "Anthropic"
    - "Cohere"
    - "Hugging Face"
    - "Stability AI"
    - "Character.AI"
    - "Adept"
    - "Inflection AI"
  
  traditional_research:
    - "IBM Research"
    - "Adobe Research"
    - "Salesforce Research"