citation_sources:
  google_scholar:
    rate_limit: 4.0
    retry_attempts: 3
    timeout: 30
    use_browser_automation: true
    manual_captcha_intervention: true
  
  semantic_scholar:
    rate_limit: 0.1
    retry_attempts: 3
    timeout: 30
    api_key: null
  
  openalex:
    rate_limit: 0.05
    retry_attempts: 3
    timeout: 30

pdf_discovery:
  doi_resolver:
    email: null  # Required for CrossRef and Unpaywall APIs
    rate_limit: 0.5  # Combined rate limit for both APIs
    retry_attempts: 3
    timeout: 120

collection_targets:
  papers_per_domain_year: 8
  total_target_min: 360
  total_target_max: 720
  citation_threshold_base: 50

quality_thresholds:
  computational_richness_min: 0.4
  citation_reliability_min: 0.8
  institution_coverage_min: 0.3
  overall_quality_min: 0.7

logging:
  level: "INFO"
  file: "logs/milestone1.log"