version: '3.8'

services:
  grobid:
    image: lfoppiano/grobid:0.7.3
    container_name: grobid
    ports:
      - "8070:8070"
    environment:
      - JAVA_OPTS=-Xmx4g
    volumes:
      - grobid_data:/opt/grobid/grobid-home/tmp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8070/api/isalive"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  grobid_data: