name: CI

on:
  push:
    branches: [main, develop, packaging]
  pull_request:
    branches: [main, develop, packaging]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.12"
  UV_VERSION: "0.5.0"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: ${{ env.UV_VERSION }}
        enable-cache: true

    - name: Install dependencies
      run: |
        uv sync --group dev

    - name: Run tests with coverage
      run: |
        uv run pytest tests/ -v --cov=compute_forecast --cov-report=xml --cov-report=term --durations=0 --ignore=tests/performance

    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}

  pre-commit:
    name: Pre-commit
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1
