name: Update Dependencies

on:
  schedule:
    - cron: '0 6 * * 1'  # Weekly on Monday
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.12"
  UV_VERSION: "0.5.0"

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: ${{ env.UV_VERSION }}

    - name: Update dependencies
      run: |
        # Update all dependencies to latest compatible versions
        uv lock --upgrade

    - name: Run tests
      run: |
        uv sync --group dev
        uv run pytest tests/ -v --durations=0

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update dependencies"
        title: "chore: weekly dependency updates"
        body: |
          ## Weekly Dependency Update

          This PR contains automatic dependency updates.

          ### Changes
          - Updated `uv.lock` with latest compatible versions

          ### Testing
          - ✅ All tests pass with updated dependencies
        branch: deps/weekly-update
        delete-branch: true
        labels: |
          dependencies
          automated
