name: Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '30 3 * * 1'  # Weekly on Monday

env:
  PYTHON_VERSION: "3.12"
  UV_VERSION: "0.4.18"

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: ${{ env.UV_VERSION }}

    - name: Install dependencies
      run: |
        uv sync --group test --group dev

    - name: Run safety check
      run: |
        uv run pip install safety
        uv run safety check --json
      continue-on-error: true

    - name: Run bandit
      run: |
        uv run pip install bandit[toml]
        uv run bandit -r compute_forecast/ -ll
      continue-on-error: true
